In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
print(a)

[1 2 3]


In [4]:
type(a)

numpy.ndarray

In [5]:
a.shape

(3,)

In [6]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
b.shape

(2, 3)

In [13]:
c1 = np.array([0, 1, 2, 3, 4, 5])
c1

array([0, 1, 2, 3, 4, 5])

In [14]:
c2 = c1.reshape((2, 3))
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
# 浅いコピー（参照）
c3 = c2.ravel()
c3

array([0, 1, 2, 3, 4, 5])

In [17]:
# 深いコピー（コピー）
c4 = c2.flatten()
c4

array([0, 1, 2, 3, 4, 5])

In [18]:
type(a)

numpy.ndarray

In [19]:
a.dtype

dtype('int32')

In [20]:
d = np.array([1, 2], dtype = np.int16)
d

array([1, 2], dtype=int16)

In [21]:
d.dtype

dtype('int16')

In [22]:
d.astype(np.float16)
d.dtype

dtype('int16')

In [23]:
a

array([1, 2, 3])

In [24]:
a[0]

1

In [25]:
a[1:]

array([2, 3])

In [26]:
a[-1]

3

In [27]:
a[:2]

array([1, 2])

In [28]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
b[0]

array([1, 2, 3])

In [30]:
b[1,0]

4

In [32]:
# 単純に「2列目のみ表示」という認識でOK

b[:, 2]

array([3, 6])

In [33]:
b[1, :]

array([4, 5, 6])

In [34]:
b[0, 1:]

array([2, 3])

In [35]:
b[:, [0, 2]]

array([[1, 3],
       [4, 6]])

In [36]:
a

array([1, 2, 3])

In [37]:
a[2] = 4

In [38]:
a

array([1, 2, 4])

In [39]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
b[1, 2] =7
b

array([[1, 2, 3],
       [4, 5, 7]])

In [42]:
b[:, 2] = 8
b

array([[1, 2, 8],
       [4, 5, 8]])

In [43]:
a1 =a
a1

array([1, 2, 4])

In [44]:
a1[1] = 5
a1

array([1, 5, 4])

In [45]:
a

array([1, 5, 4])

In [46]:
a2 = a.copy()
a2

array([1, 5, 4])

In [47]:
a2[0] = 6
a2

array([6, 5, 4])

In [48]:
a

array([1, 5, 4])

In [49]:
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [50]:
c3 = c2.ravel()
d4 = c2.flatten()

In [51]:
c3[0] = 6
c4[1] = 7

In [52]:
c3

array([6, 1, 2, 3, 4, 5])

In [53]:
c4

array([0, 7, 2, 3, 4, 5])

In [54]:
c2

array([[6, 1, 2],
       [3, 4, 5]])

In [56]:
py_list1 = [0, 1]
py_list2 = py_list1[:]
py_list2[0] = 2

print(py_list1)
print(py_list2)

[0, 1]
[2, 1]


In [57]:
np_array1 = np.array([0, 1])
np_array2 = np_array1[:]
np_array2[0] = 2

print(np_array1)
print(np_array2)

[2 1]
[2 1]


In [58]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [61]:
f = np.random.random((3, 2))

In [62]:
f

array([[0.12110613, 0.10227678],
       [0.81739139, 0.73128597],
       [0.15569104, 0.58956942]])

In [63]:
np.random.seed(123)
np.random.random((3, 2))

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646]])

In [64]:
np.random.seed(123)

# random：行と列の位置情報（タプル）
# rand：2つの引数
np.random.rand(4, 2)

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646],
       [0.9807642 , 0.68482974]])

In [65]:
np.random.seed(123)
np.random.randint(1, 10)

3

In [67]:
# 乱数の範囲をしたいときは uniform を使う

np.random.uniform(0.0, 5.0, size = (2, 3))

array([[2.40465951, 1.96058759, 1.71589008],
       [3.64524854, 2.19286122, 0.29838948]])

In [68]:
np.random.uniform(size = (4, 3))

array([[0.39804426, 0.73799541, 0.18249173],
       [0.17545176, 0.53155137, 0.53182759],
       [0.63440096, 0.84943179, 0.72445532],
       [0.61102351, 0.72244338, 0.32295891]])

In [69]:
# 標準正規分布の乱数のときは、randnを使用する

np.random.randn(4, 2)

array([[-1.25388067, -0.6377515 ],
       [ 0.9071052 , -1.4286807 ],
       [-0.14006872, -0.8617549 ],
       [-0.25561937, -2.79858911]])

In [71]:
# 平均と標準偏差を指定した乱数を使用したいときには、normal を使用する

np.random.normal(10, 25, (2, 2))

array([[-7.49693086, 33.18656079],
       [ 5.65910793, 10.0711479 ]])

In [72]:
np.zeros(3)

array([0., 0., 0.])

In [73]:
# タプルは二重括弧

np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [74]:
np.ones(2)

array([1., 1.])

In [75]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [76]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [77]:
np.full(3, 3.14)

array([3.14, 3.14, 3.14])

In [79]:
np.full((2, 4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [80]:
np.nan

nan

In [81]:
np.array([1, 2, np.nan])

array([ 1.,  2., nan])

In [82]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [83]:
np.linspace(0, np.pi, 21)

array([0.        , 0.15707963, 0.31415927, 0.4712389 , 0.62831853,
       0.78539816, 0.9424778 , 1.09955743, 1.25663706, 1.41371669,
       1.57079633, 1.72787596, 1.88495559, 2.04203522, 2.19911486,
       2.35619449, 2.51327412, 2.67035376, 2.82743339, 2.98451302,
       3.14159265])

In [85]:
l = np.array([2, 2, 6, 1, 3])
np.diff(l)

array([ 0,  4, -5,  2])

In [86]:
print(a)
print(a1)

[1 5 4]
[1 5 4]


In [87]:
np.concatenate([a, a1])

array([1, 5, 4, 1, 5, 4])

In [88]:
b

array([[1, 2, 8],
       [4, 5, 8]])

In [89]:
b1 = np.array([[10], [20]])
b1

array([[10],
       [20]])

In [92]:
# 列方向（列A→Bの方向）

np.concatenate([b, b1], axis = 1)

array([[ 1,  2,  8, 10],
       [ 4,  5,  8, 20]])

In [93]:
np.hstack([b, b1])

array([[ 1,  2,  8, 10],
       [ 4,  5,  8, 20]])

In [94]:
b2 = np.array([30, 60, 45])
b2

array([30, 60, 45])

In [95]:
b3 = np. vstack([b, b2])

In [96]:
b3

array([[ 1,  2,  8],
       [ 4,  5,  8],
       [30, 60, 45]])

In [97]:
first, second = np.hsplit(b3, [2])

In [98]:
first

array([[ 1,  2],
       [ 4,  5],
       [30, 60]])

In [99]:
second

array([[ 8],
       [ 8],
       [45]])

In [103]:
first1, second1 = np.vsplit(b3, [2])

In [104]:
first1

array([[1, 2, 8],
       [4, 5, 8]])

In [105]:
second1

array([[30, 60, 45]])

In [106]:
b

array([[1, 2, 8],
       [4, 5, 8]])

In [107]:
b.T

array([[1, 4],
       [2, 5],
       [8, 8]])

In [108]:
a

array([1, 5, 4])

In [109]:
a[np.newaxis, :]

array([[1, 5, 4]])

In [110]:
a[:, np.newaxis]

array([[1],
       [5],
       [4]])

In [111]:
m = np.arange(0, 4)
m

array([0, 1, 2, 3])

In [113]:
n = np.arange(4, 7)
n

array([4, 5, 6])

In [117]:
xx = np.meshgrid(m)
xx

[array([0, 1, 2, 3])]

In [118]:
yy = np.meshgrid(n)
yy

[array([4, 5, 6])]

In [119]:
xx, yy = np.meshgrid(m, n)

In [120]:
# mが行方向（縦）にnの配列の長さ分コピーされる

xx

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [121]:
# nを列方向（横）にmの配列分コピーする
# その際、nの配列は縦方向にしてから、横方向に伸ばされている

yy

array([[4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6]])

In [122]:
a = np.arange(3)
b = np.arange(-3, 3).reshape((2, 3))
c = np.arange(1, 7).reshape((2, 3))
d = np.arange(6).reshape((3, 2))
e = np.linspace(-1, 1, 10)

print("a:", a)
print("b:", b)
print("c:", c)
print("d", d)
print("e", e)

a: [0 1 2]
b: [[-3 -2 -1]
 [ 0  1  2]]
c: [[1 2 3]
 [4 5 6]]
d [[0 1]
 [2 3]
 [4 5]]
e [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]


In [124]:
print('a:', a.shape)
print('b:', b.shape)
print('c:', c.shape)
print('d:', d.shape)
print('e:', e.shape)

a: (3,)
b: (2, 3)
c: (2, 3)
d: (3, 2)
e: (10,)


In [125]:
np.abs(b)

array([[3, 2, 1],
       [0, 1, 2]])

In [130]:
li = [[-3, -2, -1],
     [0, 1, 2]]
new = []

# enumerateでインデックス番号・データの2つを取得する

for i, j in enumerate(li):
    new.append([])
    for k in j:
        new[i].append(abs(k))

In [131]:
new

[[3, 2, 1], [0, 1, 2]]

In [132]:
np.abs(b)

array([[3, 2, 1],
       [0, 1, 2]])

In [133]:
np.sin(e)

array([-0.84147098, -0.70169788, -0.52741539, -0.3271947 , -0.11088263,
        0.11088263,  0.3271947 ,  0.52741539,  0.70169788,  0.84147098])

In [134]:
np.cos(e)

array([0.54030231, 0.71247462, 0.84960756, 0.94495695, 0.99383351,
       0.99383351, 0.94495695, 0.84960756, 0.71247462, 0.54030231])

In [135]:
np.log(a)

C:\Users\Owner\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718])

In [136]:
np.log10(c)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125]])

In [137]:
np.exp(a)

array([1.        , 2.71828183, 7.3890561 ])

In [138]:
a

array([0, 1, 2])

In [139]:
a + 10

array([10, 11, 12])

In [140]:
b

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [141]:
a +b

array([[-3, -1,  1],
       [ 0,  2,  4]])

In [142]:
a1 = a[:, np.newaxis]
a1

array([[0],
       [1],
       [2]])

In [143]:
a + a1

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [144]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [145]:
c - np.mean(c)

array([[-2.5, -1.5, -0.5],
       [ 0.5,  1.5,  2.5]])

In [147]:
b * 2

array([[-6, -4, -2],
       [ 0,  2,  4]])

In [148]:
b ** 3

array([[-27,  -8,  -1],
       [  0,   1,   8]], dtype=int32)

In [149]:
b -a

array([[-3, -3, -3],
       [ 0,  0,  0]])

In [150]:
a * b

array([[ 0, -2, -2],
       [ 0,  1,  4]])

In [151]:
a / c

array([[0.        , 0.5       , 0.66666667],
       [0.        , 0.2       , 0.33333333]])

In [152]:
c / a

C:\Users\Owner\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, 2. , 1.5],
       [inf, 5. , 3. ]])

In [153]:
c / (a + 1e-6)

array([[1.00000000e+06, 1.99999800e+00, 1.49999925e+00],
       [4.00000000e+06, 4.99999500e+00, 2.99999850e+00]])

In [154]:
np.dot(b, a)

array([-4,  5])

In [155]:
b @ a

array([-4,  5])

In [156]:
b @ d

array([[ -8, -14],
       [ 10,  13]])

In [157]:
d @ b

array([[  0,   1,   2],
       [ -6,  -1,   4],
       [-12,  -3,   6]])

In [158]:
a > 1

array([False, False,  True])

In [159]:
b > 0

array([[False, False, False],
       [False,  True,  True]])

In [160]:
np.count_nonzero(b > 0)

2

In [161]:
np.sum(b > 0)

2

In [162]:
np.any(b > 0)

True

In [163]:
np.all(b > 0)

False

In [164]:
b[b > 0]

array([1, 2])

In [165]:
b == c

array([[False, False, False],
       [False, False, False]])

In [166]:
a == b

array([[False, False, False],
       [ True,  True,  True]])

In [167]:
(b == c) | (a == b)

array([[False, False, False],
       [ True,  True,  True]])

In [169]:
b[(b == c) | (a == b)]

array([0, 1, 2])

In [170]:
np.allclose(b, c)

False

In [171]:
np.allclose(b, c, atol = 10)

True

In [173]:
np.sum(a)

3

In [174]:
a.sum()

3