## 3.5　出力層の設計

In [1]:
import numpy as np

### 3.5.1　恒等関数とソフトマックス関数

In [2]:
a = np.array([0.3, 2.9, 4.0])

exp_a = np.exp(a)
print(exp_a)

sum_exp_a = np.sum(exp_a)
print(sum_exp_a)

y = exp_a / sum_exp_a
print(y)

[ 1.34985881 18.17414537 54.59815003]
74.1221542101633
[0.01821127 0.24519181 0.73659691]


以下のように対応している。

$a_1=0.3$、$a_2=2.9$、$a_3=4.0$<br>
$y_1=0.018$、$y_2=0.24$、$y_3=0.7$

In [3]:
def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y

### 3.5.2　ソフトマックス関数の実装上の注意

In [4]:
a = np.array([1010, 1000, 990])
np.exp(a) / np.sum(np.exp(a))

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan, nan, nan])

$c$ に $a$ の最大値を代入する。

In [5]:
c = np.max(a)
a - c

array([  0, -10, -20])

In [6]:
np.exp(a - c) / np.sum(np.exp(a - c))

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])

In [7]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y

In [8]:
softmax(a)

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])

### 3.5.3　ソフトマックス関数の特徴

In [9]:
a = np.array([0.3, 2.0, 4.0])
y = softmax(a)

print(y)
print(np.sum(y))

[0.0213123  0.11666243 0.86202526]
1.0


ソフトマックス関数の出力の総和は1になる。

ニューラルネットワークのクラス分類では、一般的に、出力の 1 番大きいニューロンに相当するクラスだけを認識結果とする。<br>
そして、ソフトマックス関数を適用しても、出力の 1 番大きいニューロンの場所は変わらない。<br>
そのため、ニューラルネットワークが分類を行う際には、出力層のソフトマックス関数を省略することができ、それが一般的である。

### 3.5.4　出力層のニューロンの数

クラス分類を行う問題では、出力層のニューロンの数は、分類したいクラスの数に設定するのが一般的である。