In [72]:
import numpy as np

In [73]:
a = np.array([1, 2, 3])

In [74]:
type(a)

numpy.ndarray

In [75]:
a.dtype

dtype('int32')

In [76]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [79]:
np.random.seed(123)

f = np.random.random((3, 2))
f

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646]])

In [80]:
np.random.seed(123)

np.random.rand(3, 2)

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646]])

In [81]:
np.random.randint(1, 10)

7

In [82]:
np.random.randint(1, 10, ((3, 3)))

array([[2, 1, 2],
       [1, 1, 4],
       [5, 1, 1]])

In [83]:
# uniformは数字範囲を自由に指定できる

np.random.uniform(0.0, 5.0, size = (2, 3))

array([[3.68997703, 0.91245865, 0.87725878],
       [2.65775687, 2.65913794, 3.17200479]])

In [84]:
# デフォルトで0.0以上1.0未満となる

np.random.uniform(size = (4, 3))

array([[0.84943179, 0.72445532, 0.61102351],
       [0.72244338, 0.32295891, 0.36178866],
       [0.22826323, 0.29371405, 0.63097612],
       [0.09210494, 0.43370117, 0.43086276]])

In [85]:
np.random.seed(123)

np.random.randn(4, 2)

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654],
       [-2.42667924, -0.42891263]])

In [86]:
np.random.seed(123)

np.random.normal(0, 1, (4, 2))

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654],
       [-2.42667924, -0.42891263]])

In [87]:
# full は後ろに数字、前に数字の配列形態がくる

np.full(3, 3.14)

array([3.14, 3.14, 3.14])

In [88]:
np.full((2, 4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [89]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [90]:
l = np.array([2, 2, 6, 1, 3])

np.diff(l)

array([ 0,  4, -5,  2])

In [91]:
a = np.array([1, 5, 4])

a1 = a

In [92]:
np.concatenate([a, a1])

array([1, 5, 4, 1, 5, 4])

In [93]:
# 次元が1つなら、axis = 0 でも自動的にその1つ（横結合）となる

np.concatenate([a, a1], axis = 0)

array([1, 5, 4, 1, 5, 4])

In [94]:
# 次元を増やしてみる

a = np.array([[1, 5, 4]])
a1 = a

np.concatenate([a, a1], axis = 0)

array([[1, 5, 4],
       [1, 5, 4]])

In [95]:
np.concatenate([a, a1], axis = 1)

array([[1, 5, 4, 1, 5, 4]])

In [96]:
# concatenateのaxisを省略して書ける

np.vstack([a, a1])

array([[1, 5, 4],
       [1, 5, 4]])

In [97]:
np.hstack([a, a1])

array([[1, 5, 4, 1, 5, 4]])

In [98]:
b3 = np.array([[1, 2, 8], [4, 5, 8], [30, 60, 45]])
b3

array([[ 1,  2,  8],
       [ 4,  5,  8],
       [30, 60, 45]])

In [99]:
first, second = np.hsplit(b3, [2])
first

array([[ 1,  2],
       [ 4,  5],
       [30, 60]])

In [100]:
second

array([[ 8],
       [ 8],
       [45]])

In [101]:
first, second = np.vsplit(b3, [2])
first

array([[1, 2, 8],
       [4, 5, 8]])

In [102]:
second

array([[30, 60, 45]])

In [103]:
m = np.array([0, 1, 2, 3])
n = np.array([4, 5, 6])

meshgrid

①mを横1列、nを縦1列に変形する<br>
②mは全部でnの行×列数になるよう縦に伸び、nは全部でmの行×列数になるように横に伸びる

In [104]:
# nは3×1なので、全部で3行（縦）となるように伸びる

xx, yy = np.meshgrid(m, n)
xx

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [105]:
# mは4×1なので、全部で4列（横）となるように伸びる

yy

array([[4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6]])

In [106]:
l = np.array([[4], [5], [6]])
l

array([[4],
       [5],
       [6]])

In [107]:
# lは3×1なので、縦に全部で3行となるように伸びる

xx, yy = np.meshgrid(m, l)
xx

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [108]:
# mは4×1なので、横に全部で4行となるように伸びる

yy

array([[4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6]])

In [109]:
k = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
k

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [110]:
# kは3×3=9 なので、縦に全部で9行となるように伸びる

xx, yy = np.meshgrid(m, k)
xx

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [111]:
# kを全部縦1列にして、全部で横が4列となるように伸ばす

yy

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6],
       [7, 7, 7, 7],
       [8, 8, 8, 8],
       [9, 9, 9, 9]])

In [112]:
# kを全部横1列にして、全部で縦に4行となるように伸ばす

xx, yy = np.meshgrid(k, m)
xx

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [113]:
# mを全部縦1列にして、全部で横に9列となるように伸ばす

yy

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3]])