## 2.3　ニューラルネットワークの歯車：テンソル演算

In [1]:
import time
import numpy as np
import matplotlib.pyplot as plt
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist

### 2.3.1　要素ごとの演算

In [2]:
def naive_relu(x):
  assert len(x.shape) == 2
  x = x.copy()
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i, j] = max(x[i, j], 0)
  return x

In [3]:
def naive_add(x, y):
  assert len(x.shape) == 2
  assert x.shape == y.shape
  x = x.copy()
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i, j] += y[i, j]
  return x

In [4]:
x = np.random.random((20, 100))
y = np.random.random((20, 100))
t0 = time.time()
for _ in range(1000):
  z = x + y
  z = np.maximum(z, 0)
print('Took: {0:.2f} s'.format(time.time() - t0))

Took: 0.02 s


In [5]:
t0 = time.time()
for _ in range(1000):
  z = naive_add(x, y)
  z = naive_relu(z)
print('Took: {0:.2f} s'.format(time.time() - t0))

Took: 5.59 s


### 2.3.2　ブロードキャスト

In [6]:
y = np.random.random((32, 10))
y = np.random.random((10,))
print(x.shape)
print(y.shape)

(20, 100)
(10,)


In [7]:
y = np.expand_dims(y, axis=0)
print(y.shape)

(1, 10)


In [8]:
γ = np.concatenate([y] * 32, axis=0)
print(γ.shape)

(32, 10)


In [9]:
def naive_add_matrix_and_vector(x, y):
  assert len(x.shape) == 2
  assert len(y.shape) == 1
  assert x.shape[1] == y.shape[0]
  x = x.copy()
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i, j] += y[j]
  return x

In [10]:
x = np.random.random((64, 3, 32, 10))
y = np.random.random((32, 10))
z = np.maximum(x, y)
print(x.shape)
print(y.shape)
print(z.shape)

(64, 3, 32, 10)
(32, 10)
(64, 3, 32, 10)


### 2.3.3　テンソル積

In [11]:
x = np.random.random((32,))
y = np.random.random((32,))
z = np.dot(x, y)

In [12]:
def naive_vector_dot(x, y):
  assert len(x.shape) == 1
  assert len(y.shape) == 1
  assert x.shape[0] == y.shape[0]
  z = 0
  for i in range(x.shape[0]):
    z += x[i] * y[i]
  return z

In [13]:
def naive_matrix_vector_dot(x, y):
  assert len(x.shape) == 2
  assert len(y.shape) == 1
  assert x.shape[1] == y.shape[0]
  z = np.zeros(x.shape[0])
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      z[i] += x[i, j] * y[j]
  return z

In [14]:
def naive_matrix_vector_dot(x, y):
  z = np.zeros(x.shape[0])
  for i in range(x.shape[0]):
    z[i] = naive_vector_dot(x[i, :], y)
  return z

In [15]:
def naive_matrix_dot(x, y):
  assert len(x.shape) == 2
  assert len(y.shape) == 2
  assert x.shape[1] == y.shape[0]
  z = np.zeros((x.shape[0]), y.shape[1])
  for i in range(x.shape[0]):
    for j in range(y.shape[1]):
      row_x = x[i, :]
      column_y = y[:, j]
      z[i, j] = naive_vector_dot(row_x, column_y)
  return z

### 2.3.4　テンソルの変形

In [16]:
x = np.array([[0, 1],
              [2, 3,],
              [4, 5]])
print(x.shape)
x

(3, 2)


array([[0, 1],
       [2, 3],
       [4, 5]])

In [17]:
x = x.reshape((6, 1))
print(x.shape)
x

(6, 1)


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [18]:
x = x.reshape((2, 3))
print(x.shape)
x

(2, 3)


array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
x = np.zeros((300, 20))
print(x.shape)
x = np.transpose(x)
print(x.shape)

(300, 20)
(20, 300)
