## 1.2 ニューラルネットワークの推論

In [1]:
import numpy as np

### 1.2.1　ニューラルネットワークの推論の全体図

In [2]:
x = np.random.randn(10, 2)
W1 = np.random.randn(2, 4)
b1 = np.random.randn(4)
h = np.dot(x, W1) + b1

print(x.shape)
print(W1.shape)
print(b1.shape)
print(h.shape)
h

(10, 2)
(2, 4)
(4,)
(10, 4)


array([[ 1.74631687,  0.04133774,  2.08017289,  0.04783261],
       [-0.33820737,  1.03636798,  2.03546571,  2.02121008],
       [-0.39701029,  0.59140653,  1.22118718,  2.1714781 ],
       [ 1.25361292,  0.52425014,  2.49537988,  0.46472369],
       [ 0.5569919 , -1.44128637, -1.46933727,  1.58378609],
       [ 0.3583681 ,  0.0287199 ,  0.89000774,  1.49679668],
       [ 0.40435557,  0.51202388,  1.75939819,  1.35221612],
       [ 0.49069814,  0.47843492,  1.77435702,  1.26895224],
       [ 0.27151118, -1.91116543, -2.51727696,  1.97526795],
       [ 2.06178002, -0.53121508,  1.36168272, -0.16642126]])

`b` はブロードキャストを用いて加算している。

In [3]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [4]:
x = np.random.randn(10, 2)
W1 = np.random.randn(2, 4)
b1 = np.random.randn(4)
W2 = np.random.randn(4, 3)
b2 = np.random.randn(3)
h = np.dot(x, W1) + b1
a = sigmoid(h)
s = np.dot(a, W2) * b2

print(x.shape)
print(W1.shape)
print(b1.shape)
print(h.shape)
print(s.shape)

(10, 2)
(2, 4)
(4,)
(10, 4)
(10, 3)


`x` は 2 次元のデータが 10 個、ミニバッチとしてまとめられていることを意味する。<br>
`s` は、10 個のデータがまとめて 3 次元に変換されたということである。<br>
つまり、**行はミニバッチ数、列が次元でありニューロンの数**となる。

### 1.2.2　レイヤとしてのクラス化と順伝播の実装

ニューラルネットワークにおいて、**推論は順伝播、学習は逆伝播**に相当する。

In [5]:
class Sigmoid:
    def __init__(self):
        self.params = []
        
    def forward(self, x):
        return 1 / (1 + np.exp(-x))

In [6]:
class Affine:
    def __init__(self, W, b):
        self.params = [W, b]
        
    def forward(self, x):
        W, b = self.params
        out = np.dot(x, W) + b
        return out

`Affine` は、レイヤとして使用する際に、`Affine(W, b)` のように引数を入れる必要がある。

In [7]:
class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size):
        I, H, O = input_size, hidden_size, output_size
        
        W1 = np.random.randn(I, H)
        b1 = np.random.randn(H)
        W2 = np.random.randn(H, O)
        b2 = np.random.randn(O)
        
        self.layers = [Affine(W1, b1), Sigmoid(), Affine(W2, b2)]
        
        self.params = []
        for layer in self.layers:
            self.params += layer.params
            
        print('W1')
        print(self.params[0])
        print('b1')
        print(self.params[1])
        print('W2')
        print(self.params[2])
        print('b2')
        print(self.params[3])
            
    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x

`self.params` には、すべての重みをリストにまとめている。

In [8]:
x = np.random.randn(10, 2)
model = TwoLayerNet(2, 4, 3)
s = model.predict(x)

W1
[[-0.68217718  1.53681894  1.11989444  0.75638256]
 [-0.55702698 -0.39163007  0.15778702  0.58297981]]
b1
[ 1.16889409 -0.82724934  0.95974211  0.81922125]
W2
[[ 1.59929359 -0.00883219  0.14164042]
 [ 0.37374822 -0.49358794 -0.0168574 ]
 [-1.18686907  1.1992656  -1.03587989]
 [-2.12479081 -2.17982889  0.01887863]]
b2
[-0.50495549  1.35585606 -1.55077148]


In [9]:
print(s.shape)
print(s)

(10, 3)
[[-0.61719925  0.92802945 -2.02903745]
 [-2.47093898  0.15350584 -2.43475413]
 [-1.00338617  0.75589767 -2.22352666]
 [-1.72171392  0.36272921 -2.06297128]
 [-1.58093047  0.47698816 -2.31339904]
 [-1.12982556  0.66151413 -2.04799138]
 [-0.6093891   0.78987177 -1.87684573]
 [-1.78794997  0.45092629 -2.2066148 ]
 [-0.18792045  0.69996178 -1.63657334]
 [-0.53129408  0.84531155 -1.87833096]]
