## 3.1　推論ベースの手法とニューラルネットワーク

In [1]:
import sys
import numpy as np

In [2]:
sys.path.append('../input/deeplearningfromscratch2master/deep-learning-from-scratch-2-master')

In [3]:
from common.layers import MatMul

### 3.1.3　ニューラルネットワークにおける単語の処理方法

In [4]:
c = np.array([1, 0, 0, 0, 0, 0, 0])
W = np.random.randn(7, 3)
h = np.dot(c, W)

print('C')
print(c)
print('W')
print(W)
print('h')
print(h)

C
[1 0 0 0 0 0 0]
W
[[ 0.38195308 -1.04431733  0.57852854]
 [ 0.18242308 -1.85629848 -2.24142461]
 [-1.64884369 -0.28013758  1.11099481]
 [-0.2927067   0.17678182  0.1233994 ]
 [ 1.62724595  0.13396386  0.32548187]
 [ 0.0182595   0.85973084  1.2849385 ]
 [-0.05293262  0.93596607 -0.46601532]]
h
[ 0.38195308 -1.04431733  0.57852854]


`W` の 1 行目には 1 を掛けるが、それ以降の行には 0 が掛けられるので、結果的に `W` の1 行目だけが計算される。

In [5]:
layer = MatMul(W)
h = layer.forward(c)
print(h)

[ 0.38195308 -1.04431733  0.57852854]
