## 3.4.6　順位への変換

In [1]:
import numpy as np
import pandas as pd

In [2]:
x = [10, 20, 30, 0, 40, 40]

In [3]:
rank = pd.Series(x).rank()
print(rank.values)

[2.  3.  4.  1.  5.5 5.5]


`np.argsort` は、昇順に並べ替えたときのインデックスを返す。

In [4]:
order = np.argsort(x)
rank = np.argsort(order)

print(order)
print(rank)

[3 0 1 2 4 5]
[1 2 3 0 4 5]
