## 1.2　コンテナデータ型の変数にご用心

In [1]:
import torch
import numpy as np

In [2]:
x = np.array([5, 7, 9])
y = x

print(x)
print(y)

[5 7 9]
[5 7 9]


In [3]:
x[1] = -1

print(x)
print(y)

[ 5 -1  9]
[ 5 -1  9]


In [4]:
x = np.array([5, 7, 9])
y = x.copy()
x[1] = -1

print(x)
print(y)

[ 5 -1  9]
[5 7 9]


In [5]:
x1 = torch.ones(5)
print(x1)

x2 = x1.data.numpy()
print(x2)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [6]:
x1[1] = -1

print(x1)
print(x2)

tensor([ 1., -1.,  1.,  1.,  1.])
[ 1. -1.  1.  1.  1.]


In [7]:
x1 = torch.ones(5)
x2 = x1.data.numpy().copy()
x1[1] = -1

print(x1)
print(x2)

tensor([ 1., -1.,  1.,  1.,  1.])
[1. 1. 1. 1. 1.]
