## 2.2　テンソル

In [1]:
import torch
import numpy as np

In [2]:
r0 = torch.tensor(1.0).float()
print(type(r0))
print(r0.dtype)

<class 'torch.Tensor'>
torch.float32


In [3]:
print(r0.shape)
print(r0.data)

torch.Size([])
tensor(1.)


In [4]:
r1_np = np.array([1, 2, 3, 4, 5])
print(r1_np.shape)

r1 = torch.tensor(r1_np).float()

print(r1.dtype)
print(r1.shape)
print(r1.data)

(5,)
torch.float32
torch.Size([5])
tensor([1., 2., 3., 4., 5.])


In [5]:
r2_np = np.array([[1, 5, 6], [4, 3, 2]])
print(r2_np.shape)

r2 = torch.tensor(r2_np).float()

print(r2.shape)
print(r2.data)

(2, 3)
torch.Size([2, 3])
tensor([[1., 5., 6.],
        [4., 3., 2.]])


In [6]:
torch.manual_seed(123)

r3 = torch.randn((3, 2, 2))
print(r3.shape)
print(r3.data)

torch.Size([3, 2, 2])
tensor([[[-0.1115,  0.1204],
         [-0.3696, -0.2404]],

        [[-1.1969,  0.2093],
         [-0.9724, -0.7550]],

        [[ 0.3239, -0.1085],
         [ 0.2103, -0.3908]]])


In [7]:
r4 = torch.ones((2, 3, 2, 2))
print(r4.shape)
print(r4.data)

torch.Size([2, 3, 2, 2])
tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])


In [8]:
r5 = r1.long()
print(r5.dtype)
print(r5)

torch.int64
tensor([1, 2, 3, 4, 5])


In [9]:
r6 = r3.view(3, -1)
print(r6.shape)
print(r6.data)

torch.Size([3, 4])
tensor([[-0.1115,  0.1204, -0.3696, -0.2404],
        [-1.1969,  0.2093, -0.9724, -0.7550],
        [ 0.3239, -0.1085,  0.2103, -0.3908]])


In [10]:
r7 = r3.view(-1)
print(r7.shape)
print(r7.data)

torch.Size([12])
tensor([-0.1115,  0.1204, -0.3696, -0.2404, -1.1969,  0.2093, -0.9724, -0.7550,
         0.3239, -0.1085,  0.2103, -0.3908])


In [11]:
print('requires_grad: ', r1.requires_grad)
print('device: ', r1.device)

requires_grad:  False
device:  cpu


In [12]:
item = r0.item()
print(type(item))
print(item)

<class 'float'>
1.0


In [13]:
t1 = torch.ones(1)
print(t1.shape)
print(t1.item())

torch.Size([1])
1.0


In [14]:
print(r2)
print(r2.max())

tensor([[1., 5., 6.],
        [4., 3., 2.]])
tensor(6.)


In [15]:
print(torch.max(r2, 1))

torch.return_types.max(
values=tensor([6., 4.]),
indices=tensor([2, 0]))


In [16]:
print(torch.max(r2, 1)[1])

tensor([2, 0])


In [17]:
r2_np = r2.data.numpy()
print(type(r2_np))
print(r2_np)

<class 'numpy.ndarray'>
[[1. 5. 6.]
 [4. 3. 2.]]
