## 1.2　ニューラルネットワークの推論

In [1]:
import numpy as np

### 1.2.1　ニューラルネットワークの推論の全体図

In [2]:
x = np.random.randn(10, 2)
W1 = np.random.randn(2, 4)
b1 = np.random.randn(4)
h = np.dot(x, W1) + b1

print(x.shape)
print(W1.shape)
print(b1.shape)
print(h.shape)

(10, 2)
(2, 4)
(4,)
(10, 4)


列の数から、入力層のニューロンは 2 つである。

In [3]:
print(x)

[[-0.34278603  2.28012724]
 [-0.89611176  0.71173564]
 [ 1.24746525  0.38753727]
 [-1.19367525  0.04417855]
 [-0.24864817 -1.60161635]
 [-0.27426691  0.51825811]
 [ 1.0687191  -0.70046468]
 [ 0.03144597  0.18922447]
 [-0.98389596 -0.74562886]
 [ 0.28830939 -0.45913095]]


列の数から、出力層のニューロンは 4 つである。

In [4]:
print(h)

[[-3.54565671 -3.31929684  1.46254019 -1.74548241]
 [-1.35877473 -1.46173235  1.66535881 -2.15424779]
 [-0.7109874   0.89015962 -1.13215168  0.23071129]
 [-0.43334773 -0.72517427  1.829715   -2.39609405]
 [ 1.99372104  2.55375419  0.12398581 -1.1564651 ]
 [-1.02917478 -0.63112275  0.82255591 -1.44992859]
 [ 0.82384481  2.35751642 -1.24937251  0.17145889]
 [-0.53382223  0.12619234  0.33468684 -1.07437915]
 [ 0.71025915  0.63593832  1.31764688 -2.06776734]
 [ 0.41230706  1.31731502 -0.19212726 -0.71227023]]


In [5]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [6]:
W2 = np.random.randn(4, 3)
b2 = np.random.randn(3)

a = sigmoid(h)
s = np.dot(a, W2)

print(h.shape)
print(W2.shape)
print(s.shape)

(10, 4)
(4, 3)
(10, 3)


### 1.2.2　レイヤとしてのクラス化と順伝播の実装

In [7]:
class Sigmoid:
    def __init__(self):
        self.params = []
        
    def forward(self, x):
        return 1 / (1 + np.exp(-x))

In [8]:
class Affine:
    def __init__(self, W, b):
        self.params = [W, b]
        
    def forward(self, x):
        W, b = self.params
        out = np.dot(x, W) + b
        return out

In [9]:
class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size):
        I, H, O = input_size, hidden_size, output_size
        
        W1 = np.random.randn(I, H)
        b1 = np.random.randn(H)
        W2 = np.random.randn(H, O)
        b2 = np.random.randn(O)
        
        self.layers = [Affine(W1, b1), Sigmoid(), Affine(W2, b2)]
        
        self.params = []
        for layer in self.layers:
            self.params += self.params
            
    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x

パラメータの連結は、以下のように行われている。

In [10]:
a = ['A', 'B']
a += ['C', 'D']
print(a)

['A', 'B', 'C', 'D']


In [11]:
x = np.random.randn(10, 2)
model = TwoLayerNet(2, 4, 3)
s = model.predict(x)

print(s.shape)
print(s)

(10, 3)
[[ 0.39876298 -2.19994332  1.06283883]
 [ 1.2349216  -2.26753972  0.61380018]
 [ 0.16251957 -2.1208273   1.1947324 ]
 [-0.53848172 -1.71346105  1.53117926]
 [ 0.9252974  -2.25756055  0.73767117]
 [-0.93707981 -2.49610651  1.52814495]
 [-0.04504725 -2.17698135  1.27783218]
 [ 0.13226657 -2.19014753  1.19942071]
 [ 1.0752527  -2.14398621  0.70245096]
 [ 0.32878689 -2.32616895  1.06724481]]


バッチの数（10）だけ、3 層のデータが出力されている。